### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by AlexanderHinnant** [lukakerr/markr#2]
I downloaded the app source code and opened it in Xcode. When I opened the app project for the first time, Xcode spent some time installing libraries; however since this was my first time opening Xcode in about a week I'm not sure if that was related to the app or not. Either way, once I had the project open I could not built it because the "Down" module was missing.

macOS version 10.13.14 High Sierra, Xcode version 9.3

**Comment by lukakerr** [comment]
You need to run `pod install` in your terminal inside the Markr/ directory to install the cocoapod Down. Then open the xcworkspace not xcproject

**Comment by AlexanderHinnant** [comment]
Thanks!

**Comment by lukakerr** [comment]
@AlexanderHinnant I've also just created a v0.0.0 release for Markr including a .zip download file https://github.com/lukakerr/markr/releases/tag/v0.0.0
